<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Iniciar sesin</name>
   <tag></tag>
   <elementGuidId>b2fb25b7-dd1b-4cce-9b80-19d9163e70ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginHeader > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginHeader']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe1fe1dd-7417-4a17-8c50-24b2731e48b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>fdd55817-4a67-4012-9299-001f519cb37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d6d9cbc5-fbd3-4c94-9232-a56a465020c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: title</value>
      <webElementGuid>8697646b-d603-48b3-8d6a-26c528b43946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iniciar sesión</value>
      <webElementGuid>d569bdcd-3c50-456d-8d6f-2e44cfbe71b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginHeader&quot;)/div[1]</value>
      <webElementGuid>75467f30-11c4-450d-80aa-860a4682a2c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginHeader']/div</value>
      <webElementGuid>6a138cec-cb4e-4946-8702-41315c959c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'loginHeader', '&quot;', ')/div[1]')])[1]/following::div[24]</value>
      <webElementGuid>647fa2bf-7ee3-4b2c-b070-5c2e39b34fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opciones de inicio de sesión'])[1]/preceding::div[17]</value>
      <webElementGuid>1f10b48d-b79c-4aa1-9765-3989785cedf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Términos de uso'])[1]/preceding::div[25]</value>
      <webElementGuid>e3cfd674-65f9-48e7-b9a2-402ffa8b7217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Iniciar sesión']/parent::*</value>
      <webElementGuid>7de3fab0-7f01-4fe3-80f0-0259425ee25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div</value>
      <webElementGuid>d5005f92-7c89-4daa-a83e-cdad71f0af81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Iniciar sesión' or . = 'Iniciar sesión')]</value>
      <webElementGuid>99de2b97-7917-4586-a976-f244a9105877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
