<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enviar cdigo</name>
   <tag></tag>
   <elementGuidId>ab537e4d-e76b-444a-82cf-c57cd53e3ef0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.sms-request-button.link-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form64']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d03b5424-a96c-40a7-9e08-c80a74bac480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-se</name>
      <type>Main</type>
      <value>sms-send-code</value>
      <webElementGuid>5b311c05-a6a3-471c-b75e-26f5ebd877c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button sms-request-button link-button</value>
      <webElementGuid>d7f6e9cc-4542-4320-9cd7-f8ff72cc51dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>01ccedc0-9427-4196-a5bd-b349f51abfe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enviar código</value>
      <webElementGuid>0d3421ce-26a8-4ff3-88c7-c5f8e12f9021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form64&quot;)/div[@class=&quot;o-form-content o-form-theme clearfix&quot;]/div[@class=&quot;o-form-fieldset-container&quot;]/a[@class=&quot;button sms-request-button link-button&quot;]</value>
      <webElementGuid>87c356a0-3ce7-4531-b0d3-1cc70c41536b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form64']/div/div[2]/a</value>
      <webElementGuid>51413cee-3128-43df-81cb-f818cf1c3445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enviar código')]</value>
      <webElementGuid>8a54b4b8-f725-4485-a456-72bc3074c8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autenticación por SMS'])[2]/following::a[1]</value>
      <webElementGuid>f466ed40-35b7-4c00-af3a-3ee444b9e657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okta'])[1]/preceding::a[2]</value>
      <webElementGuid>c7b562fc-cbdb-40d4-b537-484b0ac19ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Política de privacidad'])[1]/preceding::a[3]</value>
      <webElementGuid>afaf6639-87b2-4d2e-a34c-52b8d36f483b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enviar código']/parent::*</value>
      <webElementGuid>ae6302b7-6d49-4f05-9bde-e75c8cde6e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>6ac0a6b1-be76-4d22-abd2-f09f7aa43836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>50a24b53-c659-4ac7-9813-425cbd879e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Enviar código' or . = 'Enviar código')]</value>
      <webElementGuid>a6585bb6-53e5-4eee-9706-12b047f2130a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
