<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Introducir cdigo_answer</name>
   <tag></tag>
   <elementGuidId>98734a75-c00c-4cbe-8ad1-97152c244886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input71</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input71']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1bb46fd-1eac-423d-b353-c0527d1eb4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8187ad50-6f05-4baa-926d-77b801f7c432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>answer</value>
      <webElementGuid>8b02d6cc-2b52-4afc-8645-826194e0b4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input71</value>
      <webElementGuid>95e263d4-5848-4adc-8d0d-98f07a81f53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6d9d53f7-b928-4df5-926d-dc6e08e25e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input71&quot;)</value>
      <webElementGuid>5a3002fa-9c3b-43f1-a734-310fa833ec29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input71']</value>
      <webElementGuid>ff300974-2b18-4aaa-8442-3f8f032369f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form64']/div/div[2]/div/div[2]/span/input</value>
      <webElementGuid>c28f403f-9a39-45ec-ab13-8c5ac101dc9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>a8cc200d-5499-439b-be62-5579de7f9067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'answer' and @id = 'input71']</value>
      <webElementGuid>58b88c4c-b776-45dd-b4d6-6a0ce99e3333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
