<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Recordarme</name>
   <tag></tag>
   <elementGuidId>e62a1ed3-f9ec-4261-b186-c6a98009a606</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form18']/div/div[2]/div[3]/div/span/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ee79c687-0d35-43d4-b5b8-e5c333cf64e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>input41</value>
      <webElementGuid>dfedea17-5e3a-457b-8019-f7ebb70420ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-se-for-name</name>
      <type>Main</type>
      <value>remember</value>
      <webElementGuid>c8d80e33-8785-4d40-a79a-bf6863c1f255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>779eac20-8bcc-4004-b8fb-f91f8feb0251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recordarme</value>
      <webElementGuid>cfcaa14d-3854-49ab-bdc8-da9a61c9d8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form18&quot;)/div[@class=&quot;o-form-content o-form-theme clearfix&quot;]/div[@class=&quot;o-form-fieldset-container&quot;]/div[@class=&quot;o-form-fieldset o-form-label-top margin-btm-0&quot;]/div[@class=&quot;o-form-input&quot;]/span[@class=&quot;o-form-input-name-remember&quot;]/div[@class=&quot;custom-checkbox&quot;]/label[@class=&quot;hover&quot;]</value>
      <webElementGuid>6ebfec73-91c8-40c8-9088-0514933ac3aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form18']/div/div[2]/div[3]/div/span/div/label</value>
      <webElementGuid>44a5bace-c4ce-4ed6-a0b5-c141fab9edf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayuda'])[1]/preceding::label[1]</value>
      <webElementGuid>12df65c9-b4b8-4f2e-8f6c-2cfdbaab2072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okta'])[1]/preceding::label[1]</value>
      <webElementGuid>1454a01c-d6ab-4ca7-8c0a-2b90942488fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recordarme']/parent::*</value>
      <webElementGuid>fd496e7a-52f7-4aa8-9f92-54f12dc69936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/label</value>
      <webElementGuid>104e7c3d-3980-4ecd-878c-014c8750bca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Recordarme' or . = 'Recordarme')]</value>
      <webElementGuid>3b37b16d-a44a-45bf-8657-a8fa4183c2e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
